### ISSUE TITLE
使用LocalBroadcastManager替代Listener的疑问

### ISSUE THREAD

**Issue by JimmyChung1991** [jiang111/awesome-android-tips#1]
模块间有消息需要传递时，使用LocalBroadcastManager替代Listener进行模块解耦。除了解耦，这样发送消息和执行消息差一个线程循环，可以减小方法的调用链，我这就碰到一次方法调用链太长导致StackOverflow的问题。

这样发送消息和执行消息差一个线程循环。能具体解释一下嘛？没看懂

**Comment by jiang111** [comment]
比如说:AService运行在子线程,当它做完一件事以后,想要通知三到四个activity去更新数据,这时候如果你通过callback的形式来更新数据的话你需要控制callback所要更新数据的线程，这样就涉及到了(发送消息和执行消息差一个线程循环)线程之间的切换,而用广播的形式来通知activity去更新数据才更高效,也可以通过EventBus来实现
