### ISSUE TITLE
判断Fragment可见性的问题

### ISSUE THREAD

**Issue by hyfink** [jiang111/awesome-android-tips#4]
## Fragment.setUserVisibleHintFragment可以重写此方法，然后根据参数的布尔值（true的话表示当前Fragment对用户可见），来执行一些逻辑。

这个应该是错误的。
`/**
     * Set a hint to the system about whether this fragment's UI is currently visible
     * to the user. This hint defaults to true and is persistent across fragment instance
     * state save and restore.
     *
     * <p>An app may set this to false to indicate that the fragment's UI is
     * scrolled out of visibility or is otherwise not directly visible to the user.
     * This may be used by the system to prioritize operations such as fragment lifecycle updates
     * or loader ordering behavior.</p>
     *
     * @param isVisibleToUser true if this fragment's UI is currently visible to the user (default),
     *                        false if it is not.
     */
`

根据官方描述，这个方法应该让开发者主动调用来告诉系统当前fragment是否对用户可见，系统以此来处理一些界面逻辑。而不是系统根据fragment生命周期调用，所以开发者不能通过此方法判断fragment可见性。

**Comment by jiang111** [comment]
这个方法默认是true，确实是需要用户手动调用的，如果你使用fragment配合FragmentPagerAdapter使用的话,adapter会在内部控制setUserVisibleHintFragment() 这个方法(请看FragmentPagerAdapter源码) ,如果你是自己控制fragment的话，就需要手动调用setUserVisibleHintFragment() 这个方法了，谢谢提醒。
