### ISSUE TITLE
Fragment类中的onHiddenChanged(boolean)方法，使用FragmentTransaction中的hide()，show()时貌似Fragment的其它生命周期方法都不会被调用，太坑爹！

### ISSUE THREAD

**Issue by wander0552** [jiang111/awesome-android-tips#7]
会不会是重叠的原因
http://www.jianshu.com/p/c12a98a36b2b

**Comment by jiang111** [comment]
从v4包的相关类来看,我们通过FragmentTransaction的hide和show的时候,源码确实只做了hideFragment和showFragment,从FragmentTransaction实现类BackStackRecord中的hide可以看出 确实只调用了FragmentManager中的hideFragment,而FragmentManager的hideFragment处理之后只回调了Fragment中的onHiddenChanged方法。
