### ISSUE TITLE
一个排版上的小问题，其实不算问题，就是不美观

### ISSUE THREAD

**Issue by ZQiang94** [jiang111/awesome-android-tips#8]
ActivityLifecycleCallbacks接口，用于在Application类中监听各Activity的状态变化 ![阅读地址]{http://mp.weixin.qq.com/s?__biz=MzA3ODkzNzM3NQ==&mid=401277907&idx=1&sn=0b2246f5178292596fc3a8295283359c#rd}
  这里“阅读地址”的链接显示出来了。
:joy::joy::joy:

**Comment by jiang111** [comment]
好的
